version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Started installing dependencies.
      - npm install
      - echo Completed installing dependencies SUCCESSFULLY.
  build:
    commands:
      - echo Started building.
      - npm run build --workspace site
      - echo Completed building SUCCESSFULLY.
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: site/build/
